Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "../", "/opt/raccoon", create: true
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.provision "shell", path: "./bootstrap.sh"
end

